### ISSUE TITLE
spark-mongodb (0.8.0) connector is not compatible with spark-sql 1.3

### ISSUE THREAD

**Issue by msrvp** [Stratio/spark-mongodb#4]
spark-mongodb connector is not compatible with spark-sql 1.3.0.
Gives me the following error:
java.lang.IncompatibleClassChangeError: class com.stratio.deep.mongodb.MongodbRelation has interface org.apache.spark.sql.sources.PrunedFilteredScan as super class.

It works with spark-sql 1.2.

Is there a fix available for the same?

**Comment by pmadrigal** [comment]
Hi!

We are working on it. By the moment, you can download the github project and use spark-mongodb-0.8.0.jar generated in /target  after you execute "mvn clean install" in the project root directory. This should work.

Anyway, will be in central maven very soon.

Thanks!

**Comment by msrvp** [comment]
Yes, that got resolved, but has resulted in another:
java.lang.NoClassDefFoundError: com/mongodb/casbah/Imports
at com.stratio.deep.mongodb.partitioner.MongodbPartitioner.isShardedCollection(MongodbPartitioner.scala:62).
Seems like incompatibility with com.stratio.deep:deep-mongodb:0.7.0:jar.
I will try downloading this project as well from github and build it.
But do let me know if there is a solution already available.

**Comment by msrvp** [comment]
That worked, Thank you.

**Comment by pmadrigal** [comment]
It's already updated in central maven!

Thank you very much for your feedback!
