### ISSUE TITLE
version 0.8.7, load from mongodb is not working with spark 1.5.2 and 1.5.1

### ISSUE THREAD

**Issue by ganeshayadiyala** [Stratio/spark-mongodb#57]
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 131.0 failed 1 times, most recent failure: Lost task 0.0 in stage 131.0 (TID 281, localhost): java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.HiveTypeCoercion$.findTightestCommonType()Lscala/Function2;
[info] 	at com.stratio.provider.mongodb.schema.MongodbSchema.com$stratio$provider$mongodb$schema$MongodbSchema$$compatibleType(MongodbSchema.scala:85)
[info] 	at com.stratio.provider.mongodb.schema.MongodbSchema$$anonfun$4.apply(MongodbSchema.scala:49)
[info] 	at com.stratio.provider.mongodb.schema.MongodbSchema$$anonfun$4.apply(MongodbSchema.scala:49)
[info] 	at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:207)
[info] 	at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:206)
[info] 	at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:144)
[info] 	at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
[info] 	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:212)
[info] 	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:73)
[info] 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
[info] 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
[info] 	at org.apache.spark.scheduler.Task.run(Task.scala:88)
[info] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info] 	at java.lang.Thread.run(Thread.java:745)

**Comment by miguel0afd** [comment]
Hi Ganesha,

Could you provide the code that triggered the execution of this job, please?

**Comment by ganeshayadiyala** [comment]
Sorry, It took a while to figure it out where the actual problem was. It is saving the dataframe properly. But while reading that dataframe it is giving error. 

My code to read from MongoDb is 

```
val optionsMap = Map("host" ->  "localhost:27017", "database" -> "staging", "collection" -> "students1")
sqlContext.read.format("com.stratio.provider.mongodb").options(optionsMap).load().show(10)
```

**Comment by pmadrigal** [comment]
Hi Ganesha,

Version 0.8.7 supports Spark 1.4.x, if you need Spark 1.5.x you should use version 0.10.0, wich is available on maven central and github:

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spark-mongodb_2.10%22

Take a look to our first steps doc:
https://github.com/Stratio/spark-mongodb/blob/branch-0.10/doc/src/site/sphinx/First_Steps.rst

If you are using our project from spark-packages, version 0.10.x will be available there next week.

Thanks for your feedback!

**Comment by ganeshayadiyala** [comment]
Hi Pedro,

Thanks for your response. I will use 0.10.0.
